# Generated by Django 4.2.4 on 2023-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_review_article_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='main_app.author'),
        ),
    ]
