# Generated by Django 4.2.4 on 2023-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_car_owner_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
