# Generated by Django 4.2.4 on 2023-10-30 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='durations_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durations in Days'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
