# Generated by Django 4.2.4 on 2023-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_project_budget_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='durations_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in Days'),
        ),
    ]
