# Generated by Django 4.2.4 on 2023-11-09 17:21
from django.db import migrations
import random


def add_barcode(apps, schema_editor):
    products = apps.get_model("main_app", "Product")
    all_products = products.objects.all()
    all_barcodes = random.sample(
        range(100000000, 1000000000),
        len(all_products)
    )
    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()


def reverse_add_barcode(apps, schema_editor):
    products = apps.get_model("main_app", "Product")

    for product in products.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
