# Generated by Django 4.2.4 on 2023-11-09 18:15

from django.db import migrations


def get_unique_brands(apps, schema_editor):
    shoes = apps.get_model("main_app", "Shoe")
    unique_brands = apps.get_model("main_app", "UniqueBrands")

    ub_names = shoes.objects.values_list("brand", flat=True).distinct()

    for brand_name in ub_names:
        unique_brands.objects.create(brand_name=brand_name)


def remove_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model("main_app", "UniqueBrands")

    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(get_unique_brands, reverse_code=remove_unique_brands)
    ]
