# Generated by Django 4.2.4 on 2023-11-09 19:30

from django.db import migrations


def set_age_group(apps, schema_editor):
    person = apps.get_model("main_app", "Person")

    for p in person.objects.all():
        if p.age <= 12:
            p.age_group = "Child"
        elif p.age <= 17:
            p.age_group = "Teen"
        elif p.age >= 18:
            p.age_group = "Adult"
        p.save()


def set_default_group(apps, schema_editor):
    persons = apps.get_model("main_app", "Person")
    for person in persons.objects.all():
        person.age_group = "No age group"
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_default_group)
    ]
