# Generated by Django 4.2.4 on 2023-11-09 19:39

from django.db import migrations


def set_rarity(apps, schema_editor):
    items = apps.get_model("main_app", "Item")

    for item in items.objects.all():
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        elif item.price >= 31:
            item.rarity = "Mega Rare"
        item.save()


def set_default_rarity(apps, schema_editor):
    items = apps.get_model("main_app", "Item")

    for item in items.objects.all():
        item.rarity = "empty"
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=set_default_rarity)
    ]
