# Generated by Django 4.2.4 on 2023-11-09 19:48

from django.db import migrations


def generate_price(apps, schema_editor):
    MULTIPLY_PRICE = 120

    phones = apps.get_model("main_app", "Smartphone")

    for phone in phones.objects.all():
        phone.price = len(phone.brand) * MULTIPLY_PRICE
        phone.save()


def set_category(apps, schema_editor):
    phones = apps.get_model("main_app", "Smartphone")

    for phone in phones.objects.all():
        if phone.price >= 750:
            phone.category = "Expensive"
        else:
            phone.category = "Cheap"
        phone.save()

def set_price_category(apps, schema_editor):
    generate_price(apps, schema_editor)
    set_category(apps, schema_editor)


def revert_changes(apps, schema_editor):
    phones = apps.get_model("main_app", "Smartphone")

    for phone in phones.objects.all():
        phone.price = 0
        phone.category = "empty"
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_category, reverse_code=revert_changes)
    ]
