# Generated by Django 4.2.4 on 2023-11-09 19:59
from django.utils import timezone

from django.db import migrations


def update_delivery_warranty(apps, schema_editor):
    orders = apps.get_model("main_app", "Order")

    for order in orders.objects.all():
        if order.status == "Pending":
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == "Completed":
            order.warranty = "24 months"
            order.save()
        elif order.status == "Cancelled":
            order.delete()


def revert_data(apps, schema_editor):
    orders = apps.get_model("main_app", "Order")

    for order in orders.objects.all():
        if order.status == "Pending":
            order.delivery = None
        elif order.status == "Completed":
            order.warranty = "No warranty"

        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_order'),
    ]

    operations = [
        migrations.RunPython(update_delivery_warranty, reverse_code=revert_data)
    ]
